### ISSUE TITLE
Feature: User can view weapon skins and sort by collections

### ISSUE THREAD

**Issue by kbao24** [kbao24/ajax-project-2#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view weapon skins and sort by collections

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

You can search for weapon skins and view collections to see pictures and prices of the weapon skins.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-issue-1](https://github.com/kbao24/ajax-project/assets/125853028/a49ed682-dcdd-4cda-8d1c-97acc5cbcf17)
![ajax-issue-1-2](https://github.com/kbao24/ajax-project/assets/125853028/f7773162-49ff-442a-83fd-ed1e063ba032)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML Skeleton
- [x] Create the remaining HTML for the header in the `header-container` so that it matches the figma example. Make sure to take advantage of the included layout classes. 
- [x] Below the header, create the HTML for the form that creates a journal entry in the `data-view="entry-form"` element. This form needs to match the format shown in the example figma.
- [x] Complete the HTML form using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Get references to HTML elements
- [x] Add event listener for search button
- [x] Fetch API for weapon skins data
- [ ] Add a filter for matching weapon skins
- [ ] Iterate through skins in the API
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
